language: python
sudo: false
dist: trusty

python:
    - '2.7'
    # - '3.5'

cache: apt
addons:
  apt:
    packages:
    - libopenblas-dev
    - liblapack-dev
    - libhdf5-serial-dev
    # - libhdf5-7
    # - libhdf5-dev

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda

install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy anaconda-client anaconda-build
    # - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy PyYAML anaconda-client anaconda-build
    - pwd
    # - git branch -v
    # - git describe --tags --dirty
    - ./get_nanoversion.sh
    - cat __nanoversion__.txt
    - python setup.py install

script: "( cd test/phonopy ; for d in * ; do ( cd $d ; for f in test_*.py ; do python $f ; done  ) ; done; cd ../.. )"

deploy:
    # testing pypi
    - provider: pypi
      server: https://testpypi.python.org/pypi
      skip_cleanup: true
      distributions: sdist
      user: atztogo
      password:
        secure: "NDepERc9hinMkLT9r7AqywiZJ7vtxCbrPTJO1abzD4SfW3k+y256XbJNqp/7zQNhi8xplVulOkffAOHXyPTEDiNOBWsF1EE13jSFK6kLjCHTXxZ+mMgO+xHwOaHOTqdZRjsEU4gU28aObVm9/GEl2O5xLWmv5ip6rMDQZTx6enCYdo6OzlTny2WvHIjBSj0FztrWmG7hrgIsjtspyJQk/qBNoOy/fnuQ62PX7pOr9nLlQMEd9XroIzRMbsbA+u9u9KsyONtNRNldJnK542SU36lO0v/aN0fqshIEP9FQWi7KI3L3xtrKqkdj8V4YfDY+s+XeoumuFoNU8GPL2M/Eg3iYGlhwMywKU9U1UrEpKmmVg60Tai/nzpGYQF/2oTH4Zg49mYsiFi7B2oGOhJV545j4zS3g9L4hVGRFzim7PZe5cjNgH+OCVtZxY11KJebygoVn7uTRxAtDq4T2ZFYxqtshzoV7uT/lEUkriXKDIbqJd4x6idH3T5rcdEebJGfnpuBjw+sslG9JIWjl1WMBPbHEhzZNH83YUxqjmg/qJw9BZmuSW7BVxgf+5MN/pBtB8YZMnTQ2tKRI/kTvUutvzABSc0AxdkLlsM7SzCh6WAqdkQb5Sch+FhAaiDupn/gp6CAudVoSWC9WhNsB0oGgHLTmwUKkhg01eniwj40SHII="
      on:
        repo: atztogo/phonopy
        branch: rc
        tags: false
        # python: 2.7

    # testing anaconda
    - provider: script
      skip_cleanup: true
      script: conda/anaconda_deploy.sh rc $ANACONDA_TOKEN $TRAVIS_BRANCH
      on:
        repo: atztogo/phonopy
        branch: rc
        tags: false
        # python: 2.7

    # production pypi
    - provider: pypi
      skip_cleanup: true
      distributions: sdist
      user: atztogo
      password:
        secure: "sjUxbFSrhflB/NqMwcJCmalmQRX1EN4zgsK2YyY93JEk16aep+5pRyV87Q3Q54L19PGOkTqOrGyvUhwxTHUweo87F2DM1gd695bg0rROcquvhwWxlTuhMhMoUGSxDljgKbEeTvLikFd91JX2Rr/deIZLog/c3z/m55MbgHqGoyR5p1twxqLoUcJHznM8Mnn/KTauVHVQKG/6sVQr/h9AhRB8qI5VRCcrnDqAWoePqkgibWjEKchx/lmgW4TiB15IIvmIVgMxNwUa2q91Lqn3AhZDOcB/TST34yZCx8j1TpLJgAtB8+aRnTdmtfhnPWN8gebVuHJni+EQYsq4sIOiRzsU5qHkCzmW2x6I/kcTTYWYW4KybKorWQcypotTkyDoSfFuhZ93kyMy6QXBdV0/3xskBAbA++Mc93u6KaNMDnBGLb9PoeIT6R6YRNnwDAYBSlJ8lMZoNwVKrPhxI11r15eAK/4NamUHSLORBJWYKw1Z1Ko5wjkMXTSC4y7rC5UD+wrgZCfhB7WBLvatGBA3oD83dmEzMl3zA3wyaegDqHbEzKIFCGX5/eKrVN91hQrvlFkVYwf7YHAcNTvplZi0EGotfuZVsyhHiYSXRrMdF16g/NyZwunMEydafsbbwQatLxMhCMufX+5B1bk8VsmM0QDI9EV3rdvC7vgpnO5KPpY="
      on:
        branch: master
        tags: false
        # python: 2.7  

    # production anaconda
    - provider: script
      skip_cleanup: true
      script: conda/anaconda_deploy.sh main $ANACONDA_TOKEN $TRAVIS_BRANCH
      on:
        branch: master
        tags: false
        # python: 2.7
